#ifndef ADMINPAYMENTWINDOW_H
#define ADMINPAYMENTWINDOW_H

#include <QDialog> // Or <QWidget> if that's your base class

// Forward declaration of the UI class generated by uic
// This allows us to declare the 'ui' pointer below without including the full definition here.
namespace Ui {
class AdminPaymentWindow; // Make sure this matches the class name in your .ui file
}

class AdminPaymentWindow : public QDialog // Or QWidget
{
    Q_OBJECT // Essential for signals and slots

public:
    explicit AdminPaymentWindow(QWidget *parent = nullptr); // Standard constructor
    ~AdminPaymentWindow();                                 // Destructor

private slots:
               // Add slots for your UI elements here later
               // Example:
               // void on_saveAdminSettingsButton_clicked();
               // void on_cancelButton_clicked();
               // void on_userList_selectionChanged();

private:
    // Pointer to the UI definition
    // This MUST match the class name in the .ui file, prefixed with Ui::
    Ui::AdminPaymentWindow *ui;

    // Optional: Helper functions for organization
    void setupConnections();
    void loadInitialData();

};

#endif // ADMINPAYMENTWINDOW_H
